### ISSUE TITLE
CLI: make requests to mock server /language and /run endpoints

### ISSUE THREAD

**Issue by camerondurham** [camerondurham/runner#12]
CLI makes valid requests to mock server endpoints created in #6.

Resources for working with the CLI:
- link to code in this repo: https://github.com/camerondurham/runner/tree/main/cli/runner
- [Docs: Cobra Concepts](https://cobra.dev/#concepts)
- [Docs: Getting Started](https://cobra.dev/#getting-started)
- Examples:
    - [adding a command line flag to CLI](https://github.com/camerondurham/ch/blob/4bb750335485169e469bdb191c8ca29bb107b358/cmd/create.go#L171)
    - [reading what user set flag to](https://github.com/camerondurham/ch/blob/4bb750335485169e469bdb191c8ca29bb107b358/cmd/create.go#L75)

Basic requirements:
- [x] CLI makes `GET` request to `/api/v1/languages` endpoint, displays a formatted response in terminal
- [x] CLI makes `POST` request to `/api/v1/run` endpoint and displays a formatted response in terminal

Nice to have:
These can be implemented in another story

- [x] CLI loads source code file from user
- [x] CLI sends source code string in `POST /api/v1/run` request body

**Comment by camerondurham** [comment]
Good question! I believe the API should always be responsible for checking this kind of thing and let the CLI do minimal work possible by default. However, having CLI precheck language could be a convenient feature. So to answer your question, let the API do the lang check by default but you're more than welcome to put this behind a bool feature flag (you probably figured it out, but you can use `cmd.Flags().Bool(...)` for this: [example](https://github.com/camerondurham/ch/blob/4bb750335485169e469bdb191c8ca29bb107b358/cmd/create.go#L183)).

> compare it to whatever file type or language-indicating flag the user inputs

This is a cool idea to use the file type to check, I didn't think of that and I think that could make a CLI easier to use! Just one thing, I don't think we should enforce a strict file extension == language match so things don't get too complicated.  Just taking a string input with language explicitly specified is totally ok too.

**Comment by arekouzounian** [comment]
I've completed all the issue's original assignments, all that's left is:
- [ ] Complete implicit language logic before API call
